### ISSUE TITLE
Text

### ISSUE THREAD

**Issue by Krdnzbyza** [VBT-FlutterCamp/hakan_peker_onboard_view#2]
text gözden kaçmış galiba bu kısmıda app stirngs sınıfana alalım
https://github.com/VBT-FlutterCamp/hakan_peker_onboard_view/blob/6f18e722ec7cc1731400eaa1e2e9065f91afdc46/lib/feature/login/login_view.dart#L16

**Comment by hakannpeker** [comment]
evet kaçırmışım orayı düzeltiyorum
